# -*- coding: utf-8 -*-
"""Par_Impar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/JoseVitorRC/Jogo-Par-ou-Impar/blob/main/Par_Impar.ipynb
"""

import random

def validar_numero(numero):
    try:
        numero = int(numero)
        if 0 <= numero <= 10:
            return numero
        else:
            raise ValueError("Número inválido! Digite um número entre 0 e 10.")
    except ValueError as e:
        print(e)
        return None

def validar_escolha(escolha):
    if escolha in ['Par', 'Impar']:
        return escolha
    else:
        print("Escolha inválida! Digite 'Par' ou 'Impar'.")
        return None

def jogar_novamente():
    while True:
        opcao = input("\nDeseja jogar novamente? (s/n): ").strip().lower()
        if opcao == 's':
            return True
        elif opcao == 'n':
            print("\nValeu pela jogatina! Beba água.")
            return False
        else:
            print("Resposta inválida! Digite 's' para sim ou 'n' para não.")

def jogo():
    print("Jogo Par ou Ímpar bem maneiro!!")
    while True:
        nome = input("Informe seu nome: ")
        numero_usuario = None
        while numero_usuario is None:
            numero_usuario = input("\nDigite um número de 0 a 10: ")
            numero_usuario = validar_numero(numero_usuario)

        escolha_usuario = None
        while escolha_usuario is None:
            escolha_usuario = input("\nPar ou Impar? ").strip().capitalize()
            escolha_usuario = validar_escolha(escolha_usuario)

        numero_computador = random.randint(0, 10)
        resultado_final = numero_usuario + numero_computador
        resultado_tipo = "Par" if resultado_final % 2 == 0 else "Impar"

        if escolha_usuario == resultado_tipo:
            print(f"\nParabéns {nome}, Você ganhou!\nO resultado foi: {resultado_final} ({resultado_tipo})")
        else:
            print(f"\nInfelizmente {nome}, Você perdeu!\nO resultado foi: {resultado_final} ({resultado_tipo})")

        if not jogar_novamente():
            break

if __name__ == "__main__":
    jogo()